"""remove fk constraint from user_announcements

Revision ID: 0d8dbfaec0f7
Revises: 4f4bd9593651
Create Date: 2026-03-12 16:19:23.516203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8dbfaec0f7'
down_revision = '4f4bd9593651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_announcements', schema=None) as batch_op:
        batch_op.alter_column('announcement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_announcements_announcement_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_announcements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_announcements_announcement_id_fkey'), 'announcements', ['announcement_id'], ['id'])
        batch_op.alter_column('announcement_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
