"""add pending_officer_request

Revision ID: 3cd0111186ea
Revises: 7c4c9dae4967
Create Date: 2026-03-16 11:45:08.404648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd0111186ea'
down_revision = '7c4c9dae4967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_officer_request', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('pending_officer_request')

    # ### end Alembic commands ###
