"""add officer_notes to reports

Revision ID: 639d8acc4645
Revises: 7f7373765381
Create Date: 2026-03-11 13:16:25.639322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d8acc4645'
down_revision = '7f7373765381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('media_report_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notifications_created_at'))
        batch_op.drop_index(batch_op.f('idx_notifications_is_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_user_id'))
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('officer_notes')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.create_index(batch_op.f('idx_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('media_report_id_fkey'), 'reports', ['report_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
