"""add deactivation fields

Revision ID: 7d05f8c23c9b
Revises: 3cd0111186ea
Create Date: 2026-03-17 11:07:30.794736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d05f8c23c9b'
down_revision = '3cd0111186ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['deactivated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deactivated_at')
        batch_op.drop_column('deactivated_by')
        batch_op.drop_column('deactivation_reason')

    # ### end Alembic commands ###
